directories:
  output: release/${version}
  buildResources: build
$schema: https://raw.githubusercontent.com/electron-userland/electron-builder/master/packages/app-builder-lib/scheme.json
appId: YourAppID
asar: true
files:
  - filter:
      - dist-electron
      - dist
mac:
  artifactName: ${productName}_${version}.${ext}
  target:
    - dmg
win:
  target:
    - target: nsis
      arch:
        - x64
  artifactName: ${productName}_${version}.${ext}
nsis:
  oneClick: false
  perMachine: false
  allowToChangeInstallationDirectory: true
  deleteAppDataOnUninstall: false
electronVersion: 24.4.1
